version: '3'

tasks:
  coverage:
    cmds:
      - go test -coverprofile=./coverage/coverage.out -v ./...
      - go tool cover -o ./coverage/coverage.html -html=./coverage/coverage.out
      - rm ./coverage/coverage.out
  test:
    cmds:
      - go test -v ./...
  build:
    cmds:
      - go build -o ./dist/moonbite